"""
Corrige acentos e ortografia no pgrs.html usando replace simples
"""
PATH = r"C:\Users\crist\OneDrive\Área de Trabalho\Engenharia\site\site\global-match-site\pgrs.html"

SUBSTITUICOES = [
    # muito frequentes
    ("Regularizacao", "Regularização"),
    ("regularizacao", "regularização"),
    ("REGULARIZACAO", "REGULARIZAÇÃO"),
    ("Documentacao", "Documentação"),
    ("documentacao", "documentação"),
    ("Classificacao", "Classificação"),
    ("classificacao", "classificação"),
    ("Fiscalizacao", "Fiscalização"),
    ("fiscalizacao", "fiscalização"),
    ("fiscalizacoes", "fiscalizações"),
    ("Elaboracao", "Elaboração"),
    ("elaboracao", "elaboração"),
    ("Notificacao", "Notificação"),
    ("notificacao", "notificação"),
    ("Destinacao", "Destinação"),
    ("destinacao", "destinação"),
    ("Revisao", "Revisão"),
    ("revisao", "revisão"),
    ("Validacao", "Validação"),
    ("validacao", "validação"),
    ("Avaliacao", "Avaliação"),
    ("avaliacao", "avaliação"),
    ("situacoes", "situações"),
    ("SITUACOES", "SITUAÇÕES"),
    ("Solucao", "Solução"),
    ("solucao", "solução"),
    ("Gestao", "Gestão"),
    ("gestao", "gestão"),
    ("Organizacao", "Organização"),
    ("organizacao", "organização"),
    ("Identificacao", "Identificação"),
    ("identificacao", "identificação"),
    ("Emissao", "Emissão"),
    ("emissao", "emissão"),
    ("Interdicao", "Interdição"),
    ("interdicao", "interdição"),
    ("interditacoes", "interdições"),
    ("Segregacao", "Segregação"),
    ("segregacao", "segregação"),
    ("Regulacao", "Regulação"),
    ("regulacao", "regulação"),
    ("ESPECIFICA", "ESPECÍFICA"),
    ("Preparacao", "Preparação"),
    ("preparacao", "preparação"),
    ("Aprovacao", "Aprovação"),
    ("aprovacao", "aprovação"),
    ("Geracao", "Geração"),
    ("geracao", "geração"),
    ("Renovacao", "Renovação"),
    ("renovacao", "renovação"),
    ("Atualizacao", "Atualização"),
    ("atualizacao", "atualização"),
    ("Autuacao", "Autuação"),
    ("autuacao", "autuação"),
    ("Detencao", "Detenção"),
    ("detencao", "detenção"),
    ("Construcao", "Construção"),
    ("construcao", "construção"),
    ("Certificacao", "Certificação"),
    ("certificacao", "certificação"),
    ("certificacoes", "certificações"),
    ("Localizacao", "Localização"),
    ("localizacao", "localização"),
    ("Satisfacao", "Satisfação"),
    ("satisfacao", "satisfação"),
    ("Informacoes", "Informações"),
    ("informacoes", "informações"),
    ("Orientacoes", "Orientações"),
    ("orientacoes", "orientações"),
    ("Corporacoes", "Corporações"),
    ("corporacoes", "corporações"),
    ("organizacoes", "organizações"),
    ("Situacao", "Situação"),
    ("situacao", "situação"),
    ("Acao", "Ação"),
    ("acao", "ação"),

    # acentos agudos
    ("Saude", "Saúde"),
    ("saude", "saúde"),
    ("solidos", "sólidos"),
    ("Residuos", "Resíduos"),
    ("residuos", "resíduos"),
    ("Inventario", "Inventário"),
    ("inventario", "inventário"),
    ("Orcamento", "Orçamento"),
    ("orcamento", "orçamento"),
    ("Preco", "Preço"),
    ("preco", "preço"),
    ("PRECOS", "PREÇOS"),
    ("Precos", "Preços"),
    ("Obrigatorio", "Obrigatório"),
    ("obrigatorio", "obrigatório"),
    ("obrigatoria", "obrigatória"),
    ("Tecnico", "Técnico"),
    ("tecnico", "técnico"),
    ("tecnica", "técnica"),
    ("tecnicas", "técnicas"),
    ("Diagnostico", "Diagnóstico"),
    ("diagnostico", "diagnóstico"),
    ("Responsavel", "Responsável"),
    ("responsavel", "responsável"),
    ("reforcada", "reforçada"),
    ("Confianca", "Confiança"),
    ("confianca", "confiança"),
    ("Comecar", "Começar"),
    ("comecar", "começar"),
    ("Duvidas", "Dúvidas"),
    ("duvidas", "dúvidas"),
    ("mudancas", "mudanças"),
    ("Avancada", "Avançada"),
    ("avancada", "avançada"),

    # circunflexo
    ("Voce", "Você"),
    ("voce", "você"),
    ("Nivel", "Nível"),
    ("nivel", "nível"),
    ("Negocio", "Negócio"),
    ("negocio", "negócio"),
    ("impecaveis", "impecáveis"),
    ("Fisico", "Físico"),
    ("fisico", "físico"),
    ("fisicas", "físicas"),
    ("Juridicas", "Jurídicas"),
    ("juridicas", "jurídicas"),
    ("Publica", "Pública"),
    ("publica", "pública"),
    ("medias", "médias"),
    ("Medio", "Médio"),
    ("medio", "médio"),
    ("Continuo", "Contínuo"),
    ("continuo", "contínuo"),
    ("Proprietario", "Proprietário"),
    ("proprietario", "proprietário"),
    ("Proprietaria", "Proprietária"),
    ("proprietaria", "proprietária"),
    ("periodicos", "periódicos"),
    ("Consultorios", "Consultórios"),
    ("consultorios", "consultórios"),
    ("Predio", "Prédio"),
    ("predio", "prédio"),
    ("Cabeca", "Cabeça"),
    ("cabeca", "cabeça"),

    # comuns
    (" nao ", " não "),
    ("nao ", "não "),
    (" nao", " não"),
    ("Nao ", "Não "),
    (" Nao", " Não"),
    (" esta ", " está "),
    (".esta", ".está"),
    (" estao ", " estão "),
    (" esta.", " está."),
    (" esta,", " está,"),
    (" esta?", " está?"),
    (" esta!", " está!"),
    (" sao ", " são "),
    (" ate ", " até "),
    ("Ate ", "Até "),
    (" Ja ", " Já "),
    ("ja ", "já "),
    (" So ", " Só "),
    ("so ", "só "),
    ("uteis", "úteis"),
    ("Milhoes", "Milhões"),
    ("milhoes", "milhões"),
    ("Regioes", "Regiões"),
    ("regioes", "regiões"),
    ("Regiao", "Região"),
    ("regiao", "região"),
    ("Industria", "Indústria"),
    ("industria", "indústria"),
    ("Industrias", "Indústrias"),
    ("industrias", "indústrias"),
    ("Condominio", "Condomínio"),
    ("condominio", "condomínio"),
    ("Condominios", "Condomínios"),
    ("condominios", "condomínios"),
    ("Clinica", "Clínica"),
    ("clinica", "clínica"),
    ("Clinicas", "Clínicas"),
    ("clinicas", "clínicas"),
    ("Odontologica", "Odontológica"),
    ("odontologica", "odontológica"),
    ("Odontologicas", "Odontológicas"),
    ("odontologicas", "odontológicas"),
    ("Estetica", "Estética"),
    ("estetica", "estética"),
    ("Veterinarias", "Veterinárias"),
    ("veterinarias", "veterinárias"),
    ("Laboratorios", "Laboratórios"),
    ("laboratorios", "laboratórios"),
    ("Comercios", "Comércios"),
    ("comercios", "comércios"),
    ("orgaos", "órgãos"),
    ("Vigilancia", "Vigilância"),
    ("vigilancia", "vigilância"),
    ("Sanitaria", "Sanitária"),
    ("sanitaria", "sanitária"),
    ("Prioritario", "Prioritário"),
    ("prioritario", "prioritário"),
    ("Urgencia", "Urgência"),
    ("urgencia", "urgência"),
    ("Exigencia", "Exigência"),
    ("exigencia", "exigência"),
    ("exigencias", "exigências"),
    ("Ausencia", "Ausência"),
    ("ausencia", "ausência"),
    ("Experiencia", "Experiência"),
    ("experiencia", "experiência"),
    ("Logistica", "Logística"),
    ("logistica", "logística"),
    ("Quimica", "Química"),
    ("quimica", "química"),
    ("Alimenticia", "Alimentícia"),
    ("alimenticia", "alimentícia"),
    ("Credito", "Crédito"),
    ("credito", "crédito"),
    ("Cartao", "Cartão"),
    ("cartao", "cartão"),
    ("Bancario", "Bancário"),
    ("bancario", "bancário"),
    ("Transferencia", "Transferência"),
    ("transferencia", "transferência"),
    ("Precisavamos", "Precisávamos"),
    ("Estavamos", "Estávamos"),
    ("Sindica", "Síndica"),
    ("numero", "número"),
    ("Numero", "Número"),
    ("valido", "válido"),
    ("Servico", "Serviço"),
    ("servico", "serviço"),
    ("Servicos", "Serviços"),
    ("servicos", "serviços"),
    ("Maxima", "Máxima"),
    ("maxima", "máxima"),
    ("Formulario", "Formulário"),
    ("formulario", "formulário"),
    ("Fotografico", "Fotográfico"),
    ("fotografico", "fotográfico"),
    ("Tatuape", "Tatuapé"),
    ("Taboao", "Taboão"),
    ("Escritorio", "Escritório"),
    ("escritorio", "escritório"),
    ("Escritorios", "Escritórios"),
    ("escritorios", "escritórios"),
    ("Especifico", "Específico"),
    ("especifico", "específico"),
    ("especificos", "específicos"),
    ("Joao", "João"),
    ("Tambem", "Também"),
    ("tambem", "também"),
    ("ultimos", "últimos"),

    # "e" verbo ser
    ("Minha empresa e obrigada", "Minha empresa é obrigada"),
    ("Qual e", "Qual é"),
    ("Qual e o", "Qual é o"),
    ("Como e", "Como é"),
    ("O orcamento e", "O orçamento é"),
    ("PGRS e obrigatorio", "PGRS é obrigatório"),
    ("O PGRS e obrigatorio", "O PGRS é obrigatório"),
    ("o PGRSS e obrigatorio", "o PGRSS é obrigatório"),
    ("o processo e direto", "o processo é direto"),
    ("Sua empresa esta", "Sua empresa está"),

    # Sao -> São
    ("Sao Paulo", "São Paulo"),
    ("Sao Francisco", "São Francisco"),
    (" Sao ", " São "),
    (".Sao", ".São"),
    ("sao ", "são "),
    (" SECAO ", " SEÇÃO "),

    # horários
    ("08:00 as 18:00", "08:00 às 18:00"),
    ("08:00 as 12:00", "08:00 às 12:00"),

    # avulsos
    ("Disponivel", "Disponível"),
    ("disponivel", "disponível"),
    ("Apos", "Após"),
    ("apos", "após"),
    ("Também", "Também"),
    ("tambem", "também"),

    # comentarios CSS
    ("SECAO DEDICADA", "SEÇÃO DEDICADA"),
    ("SECAO", "SEÇÃO"),

    # "e" solto na linha 69
    ("\"PGRS e obrigatorio", "\"PGRS é obrigatório"),
    ("\"O PGRSS e obrigatorio", "\"O PGRSS é obrigatório"),
    ("\"PGRSS e obrigatorio", "\"PGRSS é obrigatório"),
]

with open(PATH, 'r', encoding='utf-8') as f:
    content = f.read()

original = content
total = 0

for old, new in SUBSTITUICOES:
    if old in content:
        c = content.count(old)
        content = content.replace(old, new)
        print(f"  {old} -> {new}: {c} vez(es)")
        total += c

if content != original:
    with open(PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"\n✅ Total: {total} correções aplicadas em pgrs.html")
else:
    print("⚠️ Nenhuma alteração necessária.")
